import { NextPage } from "next";
import Head from "next/head";

import Category from "../components/Category";
import LandingPage from "./LandingPage";
import Tops from "./tops";
// import Product from "./Product.tsx";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>Unoqli | One Stop Cloth Store</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>

      <LandingPage />
    </>
  );
};

export default Index;
