name: "CI"

on: [pull_request]

jobs:
  build:
    name: "Build, lint, and test"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Set up latest Node LTS"
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: "Install dependencies"
        run: npm ci

      - name: "Check format"
        run: npm run format:check

      - name: "Build"
        run: npm run build

      - name: "Lint"
        run: npm run lint

      - name: "Test"
        run: npm run test
